project:
  type: book

book:
  title: "Memoirs of a magpie"
  chapters:
    - index.qmd
    - chapter-1.qmd
    - the-big-y.qmd

format:
  html:
    theme: litera
    number-sections: false
  pdf:
    documentclass: scrreprt



