project:
  type: book
  pre-render: word_count_script.R
  preview:
    watch-inputs: false
    navigate: false

book:
  title: "Memoirs of a magpie"
  author: "Janith Wanniarachchi"
  sidebar:
    footer: word-count.md
  chapters:
    - index.qmd
    - part: "Part 1: Interacting with the world"
      chapters:
        - on-helping-others-and-expecting-help.qmd
        - on-the-unseen-board-games.qmd
    - part: "Part 2: Untangling the mind"
      chapters:
        - on-the-value-of-ones-life.qmd
        - on-the-fear-of-being-alone.qmd
        - on-chasing-dreams.qmd
        - on-meditation.qmd
        - on-beliefs-and-practices.qmd
    - part: "Part 3: My story"
      chapters:
        - on-writing.qmd
        - letters.qmd
        - suicide-notes.qmd 
  appendices:
    - the-big-y.qmd

format:
  html:
    theme:
      light: [litera, main.scss]
      dark: [darkly, main.scss]
    number-sections: true
