project:
  type: book

book:
  title: "Memoirs of a magpie"
  author: "Janith Wanniarachchi"
  chapters:
    - index.qmd
    - part: "Part 1: Interacting with the world"
      chapters:
        - on-helping-others-and-expecting-help.qmd
        - on-the-unseen-board-games.qmd
    - part: "Part 2: Untangling the mind"
      chapters:
        - on-the-value-of-ones-life.qmd
  appendices:
    - the-big-y.qmd

format:
  html:
    theme: litera
    number-sections: true
