# On the unseen board games that humans play

Humans are interesting in the way that they play different games with the people around them. Most of these games are seen in large screens and stadiums alike. But the games that go unseen a lot are the games of social interactions. Every human as they grow up builds up different standards, governing rules or presets for the social interactions that they experience. They build certain rules within them and as they grow old and meet other people who uphold similar standards these rules start solidifying gradually. Some might call these biases or some might even call these common sense.

I have been told many times that I am someone who seems to struggle to understand these social cues. I have lost many friendships due to that. Lost is a pretty dramatic word I believe and therefore a better phrase would be _broken beyond recognition_ (I'm sure there's a German word for that phrase). I would often not see or understand these social cues and overstep boundaries or say things that offend or hurt people. The fault is primarily in me, one might say, and yes, that might predominantly be the case. But reliance on social cues and common sense to work your way through social interactions can be quite harmful actually. 

Picture this, you are a professional in the field of Computer science, to the point that you are the designated IT guy wherever you go. When dealing with people with less IT knowledge, you are bound to understand that the things that you hold as common sense might not be the same for the other people. 

Now let's look at a person called Jane. Jane has lived her life learning how to talk with people by observing her parents and accepting the rules and advices that her parents gave strictly. As Jane grows up she finds like minded people that are also capable of speaking with her nonverbally the same way that she was brought up. She understands that following the inherited rules seems to work properly and she keeps on adding more rules as she grows up. Then Jane gets to meet John who has interacted with a different group of people, and John's circle of friends are quite direct in the way they communicate, they do not leave anything for nonverbal communication and are always explicit about what they are feeling. When Jane has a conversation with John, she gets annoyed that John isn't picking up on the nonverbal communication she's having with John and calls him someone without social skills or common sense. 

While non verbal communication and explicit open communication has it's place, I would advocate for the latter. Be explicit and precise in your speech by putting forth any discomfort or happiness that you felt and being specific about what you experienced and what you don't want the other person to feel. Yes it's a lot of work, and so is explaining in detail to your mother the features of her phone, but it pays off in the end. 

If ever you feel that you aren't getting non verbal communications, be direct about it and say upfront to a person, "Hey if you do ever feel uncomfortable or feel any distress from what I say while talking with you, please do tell me at that exact moment, you can directly say it without an issue. I'm asking this favor from you because I don't want to cross your boundaries and make you feel even more uncomfortable." Be upfront about these things. For an extroverted free thinker it's really hard to do this because they are used to speaking their mind openly and explicitl.