# On the value of one's life

Strangely enough, I have met quite a lot of people that seem to value the people around them than themselves. They would go above and beyond to help their inner circles stay motivated and consistent, yet rarely will they be able to do the same for themselves. There are those who do not follow the pattern and the proportions of those who do and don't are not part of this stream of thought. My focus is on those who value the people around them more than themselves. The selfless martyrs that are willing to cross oceans regardless of whether other party is willing to jump through puddles. 

Being such a person myself, I had to ask myself. Why did I come to this stage? What sort of behavior in my childhood attributed me to being a person that was willing to help others no matter what? Perhaps it could have been religious influence or the way that I observed my parents to be acting when others were under duress. Or it could be that I was primed to understand that only those who gave everything they had and asked for none were truly valued by everyone else. Regardless of the reason we are here now. They say knowing is half the battle and I do not believe knowing the reason why would give us much solace in most cases. But understanding what this issue means to our lives and how we can navigate into the future from where we are matters more in my opinion.

While the world does need more of people who are selfless and kind, continued exposure to these behaviors may cause people to erupt and go into extremes of either being completely negelctful of everyone around them or damage themselves in a way that their help can not be well received. I have been through this question quite a lot. It might be my ADHD speaking but I would sometimes go into hyperfocus mode when it comes to the people around me to the point that it becomes unhealthy for both parties as the receiving end develops a learned helplessness while the other end fights a constant battle between what their soul is telling them vs what their hearts and minds are telling them. 

It is human nature to perservere. Ask anyone who has attempted to end their life (it would be quite difficult to ask someone who succeeded) how much the human body desires to live. Try holding your breath to see how quickly you gasp for air, glad to be alive again. Try tieing a polythene bag over your head and slowly notice how your fingers automatically claw at the knot to find air to breathe. Watch how many people who were caught in between their self burn attempts would desparately try to douse themselves of the fire. Many people have chosen these examples to showcase that those who try to commit suicide actually are not genuinely trying to do it. The reason why I brought this up was because inside every person that overworks themselves to please or satisfy someone else is a battle between the heart and the soul. The heart feels emotions and wants to help the person in distress selflessly, while the soul is struggling to make room and adjust the stress levels for recovery and perservearance. Like a pendulum swinging back and forth the mind of the martyr swings between "I will do anything to help you through this." and "I hate this, can't you honestly do this by yourself?". This toxic behavior builds up to the point of bringing in another problem which I will discuss in length below. 

An interesting aspect of my thought pattern that I have come to realize after years of battling depression, is that I would put value to my life based on how much I'm capable of helping those around me. The process is pretty straightforward. First I try to selflessly help many people around me by taking up too many tasks and opportunities, which brings me to a state of being unable to work well in across all of these tasks. Any person with an ounce of sense would be screaming out that you can't have all of the tasks and still be good at all of them. That is something I have to learn slowly and as I put down my thoughts. Hopefully putting down my thought process on a book for the world to see will either help me change the way that I think or the world will give me signs that I need to change the way that I'm thinking. Anyways, once I have filled my plate, I will take this challenge head on with all of the intensity that I can muster as there is always something novel to explore. However, as I'm giving inadaquate amounts of efforts in each section my progress dims down significantly. It comes to the point where I would be feeling like I'm actually putting no value into these projects. The usual existential crisis of "What am I even doing with these things?" comes into play at full swing at this moment. As I step down into this magical land slowly the things that I have done so far start to crumble infront of me. Whatever work I have created or any good I have done in this world is reduced to pure coincidence and just luck. I might have helped someone through their toughest times but at that moment it would simply be disregarded as "just telling obvious things that anyone would have said", "I just happened to be there and anyone else could have done the same thing". It's fascinating how this happens though. It could be rooted in my childhood where I observed the pattern that once I fail to do one task, I was considered a failure regardless of the other tasks that I have done. As I have said earlier, this is not an inspection into why but rather a what can be done. Now once my mind has brought all of my work and everything I have done to zero value by categorizing the work as something that anyone could have done, it will come to a fun conclusion. 

As I mentioned earlier, I put value on my life based on how much I'm capable of helping people. Now when the value of those helping moments are dimnished I have to come to the conclusion that my life itself has no value. What use is a life that is not useful to others. But that is only a perspective that I hold on to my life and only to it. I will not be thinking the same way of the people that I'm with. In fact I would thank them many times just for being there and that what they have done is quite unique and irreplacable. 

What exactly gives value to a life? Is it truly the work that they have done for the people around them, or is it based on the energy that they bring to the people around them? These are questions that would need to be discussed in length in the upcoming pages, but for now let's explore the different ways that people value their lives. When given the question, what makes your life valuable? It raises a secondary underlying question? Why should a life be valued? The notion of a hierarchy is what brings forth a majority of inequalities and suffering. Instead of asking what makes your life valuable the real question would be to ask, what is your reason for living? If you are living simply because of someone else that is when you start giving a value to your life based on the usefulness that you have towrds others. But instead if you are living for your own self, then the value of your life only depends on the things that your heart yearns to do. And the heart can yearn for a lot of things. At our lowest moment, our heart yearns to feel connected. From what I have experienced, there is always an opportunity for a person to feel connected. Feeling connected does not necessarily mean that you need to be talking with people, although in my case that is how I connect with people. If that is the way you connect with people then you might want to stay tuned because even I'm at a loss when it comes to that stage. My initial hypothesis was that talking with people on the internet or even in a bar might be helpful. But it requires energy to get out of your low stage and walk or travel to the nearest place where people gather. That is why my next hypothesis was that it might be a good idea to simply go and join any random twitch stream and comment along with other people. You might feel a certain kindredship in the way that everyone is rooting for the same person to play the game in a certain way. 

The games that people play are certainly interesting. You can meet a bunch of people that are playing a game of pool and you can simply be in the sidelines cheering along with the rest of the crowd and as they see your enthusiasm and your cheers, they slowly open up to you. It's an interesting phenomenon that I have experienced in countries that are outside of the south asian region. It depends on the openness of the group that is playing to accept people from the outside. Generally if people are going in a tight knit group with only the idea of enjoying the moment with that group alone.
