---
title: "Letters to my child"
---

I do not know how to structure this. But I want to pursue writing up things that that I learned from my every day happenings as sort of learned lessons for my future child to read and see that life isn't always linear. Everyone is understanding things and growing as they go in life.

Date: 16th February 2025    
To: The one after my own heart     

The weather is becoming more colder even though it's supposed to be the height of summer. Waking up was hard today as it was a nice cold Sunday morning and the tendency  to just roll over and sleep was too high. I had to promise myself that I would get out of bed at 07:15AM and show up to my laptop and keyboard to write this. 
When we are young promises mean a lot for us. It's a sign of putting trust on to others, and also a way to receive trust on to yourself. When you are young, you will make promises to others and others will make promises to you as well. At first you would expect those around you to keep their promises and at a certain point you will realize that most promises don't take promises seriously. That is where the tendency comes to promise things to yourself but have no serious obligation in your head. That is where the first steps to lying to yourself starts. From there onwards anytime you promise yourself that you would stop doing a bad behavior or that you would start doing a good behavior, it will be hard for you to keep the promise. Because you have seen others dismiss promises and consider them as simple statements, and you have seen how you would promise things to others and not follow through with it. Slowly just like that you start lying to yourself.
It's crucial that you do not follow this pattern. The first step to surviving in this world is to have yourself on your side and for that you need to foster a trusting relationship with yourself. So keep in mind when you make promises to yourself, only make the promises that you know you wholeheartedly can do and if you do make a promise, follow through with it to the end.   
Aside from that, carving out a path for yourself requires a lot I will say that for sure. Right now I am at a place where I need to stand strong on my idea and push forward with it while taking in the feedback of others in a healthy manner. It's rough I must say, but it is necessary for us to be able to form an opinion of our own. It can be a struggle to find a solid foundation to rely on but do not let that discourage you. As long as you learn how to put your effort in at the right time and to go with the flow the rest of the times, it can be a lot easier to navigate. When is the right time to put in the effort and when is the right time to go with the flow. Well my dear, I wouldn't be able to find that answer for you. Only advice I can give is to listen objectively. Listen to your body objectively, listen to others objectively, listen to your mind objectively. Your body can rarely lie but your mind and those around you can. Ask nicely and your body shall respond.

Date: 17.02.2025      
To: The one after my own heart      

For some reason falling asleep when needed is a lot difficult than it may seem on the surface. I always wonder what people think about when they fall asleep. Do they think about their loved ones? Do they think about the day to be conquered tomorrow? or the day that they regret today? Do they think about the dramas and plays that they witnessed in the day itself? I will not know for sure what others are thinking, for me I try my best to picture you as best as I can to imagination. If ever you doubt whether you were the same as I imagined the answer will always be, no, you were better than what I always imagined.     
There's always an enjoyment in progressively getting better at things and finding out new things to be good at is always fun. Perhaps one of the best reasons to do something is to do it because it is good for you and doesn't harm those around you and you can keep on doing it into the future reaping the benefits of what you sowed. Might not seem motivational but in most cases whatever reason you hold on as the motivation has a tendency to either change drastically for the good and for the bad. In some cases you might realise that the reason that motivated you was not actually a healthy reason to be motivated. If you ever come across a moment like that my dear, just know that it's a feeling that I experienced quite a lot in my life. The first thing you must refrain from is beating yourself up and doubting all the progress that you made so far. When a foundation that you stand on gets taken out from you, you need to have yourself on your side first and foremost before anyone else joins your side. While the motivating factor might not have been suitable, progress is still progress, and mitigating the damage will take time and patience, but now that you have a clearer mind and a loving self, the future is going to be brighter I promise.    
Also if ever you come across something that ignites a childlike smile in you, go experience that. I can guarantee you, there will be a brief moment of euphoria and after that whether or not you continue feeling it every time will be questionable but it will be a lovely reminder for you to love the inner child within you.    

Date: 18.02.2025      
To: The one after my own heart       

Well it seems I have been bested and my ego is shattered. I thought I was right and the ideas of others were wrong. It might be the case that I can be right and wrong at the same time while also having the others be right and wrong at the same time. This is where I guess the notion of such cut and dry dualities become gray. It also could be that I am too proud to accept that I thought wrong. It might not be surprising to you my dear, to hear that your old man was a proud person. Nevertheless, I will accept this defeat with dignity. However, there's more to the story now that I made this tiny progress in the research. As to where and how the story will go is still a mystery to me as well.     
A surprising comment caught me off guard while I was having a chat with a friend of mine. "I wouldn't want to share my eggs and cucumbers with anyone yet." It was interesting  to think that being single gives you this freedom to pursue life in a way that is completely within your control and definitions. You might also come to an age and wonder "why should I give up being single for someone else?". And truth be told at the age that your old man is at now, he has no idea either. Although I must say I do fall easily for people but that is because I tend to forget the freedom that I take for granted. Perhaps with the right person it shouldn't feel like the freedom is taken away and maybe it feels a lot like there's a bit more color to the monotone freedom in your life.     
Is life simply a never ending cycle of having something and taking it for granted and then losing that said thing proceeded by an eternal fight to gain it again only to lose it after taking it for granted? Perhaps, that might be the case. As Zen Buddhists would say at your purest form your mind is said to be calm and free and yet we introduce so many other things that bring in a series of pain and suffering.      

Date: 19.02.2025      
To: The one after my own heart      

Working early morning does help it seems. I actually made some progress in the work that I was doing and to be honest it felt a lot more lively and less stressful than working late night. Something about me is slowly shifting I guess, and I'm glad that shift is happening. For you my dear there will come a point in time where you will be working all night long and still be able to function properly the next few days. Cherish those moments, because with time that skill becomes harder to maintain. Despite what people might say about playing to your energy levels, working late would be a bad idea if you have a bad history with it as your old man does.    
Speaking of bad history, I'm still not ready to fight back against the bullies within the walls of my family. I hope to god that by the time you are reading this I have either fought back or the bully had let go of their ways. Either way I have strengthened my resolve when presented with snide remarks of my self image by knowing that I look good to myself regardless of whatever happens to my self image. If my dear someday you want to love someone unconditionally, first love yourself in a way that no matter the mistakes or slip ups that you have that you will love yourself in the same way no matter what.
In other news, your old man may appear tough at times but know that he would cry over stories told in the big screen easily. Perhaps the most poignant set of events that affects me is the case of the misunderstood person shunning himself from the crowd and not being able to face them is able to face them with slow build up of courage. Perhaps there might be some link to my social anxiety or perhaps it's something deeper within me that finds this connection. Even though I might appear as someone who would always talk and check up on people, internally I too am scared to talk to people sometimes. It takes a bit of effort on my end to talk to people because of a variety of reasons sometimes.
It can be scary to be on a journey alone. For me whenever I see the stars at night I find companionship with them, where I would be greeting Orion and mapping out the rest of the night sky in reference to Orion. On some days it is mapped out through with the centaur. Have some small moments of whimsy in your life. See the beauty in the ordinary by letting go of your preconceived expectations and experiencing the moment fully. It might be a small flower blooming in between the rough concrete or it could be the traffic lights turning green in front of a tapestry of velvety clouds.
Carving a path for yourself can be scary at times. But at all times what's necessary is to understand what your strengths are and hone them. You might not know what your strengths are, the people around you might not know some parts of it, but there is always the case where you might have strengths that haven't been explored at all or didn't have the right time and guidance to be your strength. Whatever it is know that every step you take will be helping you reach a place of satisfaction, because surprisingly we get to decide where our place of satisfaction is at.     

Date: 20.02.2025    
To: The one after my own heart     

It is true that when you announce to the world that you are doing something, every possible method of resistance will come forth to deny you of what you are trying to achieve. This is why I think the archers in Japan would say that you have to release the arrow without realizing it. The moment you force it and announce it to the world then it would drain you out in reaching the target. Should you be hiding your ambitions and goals in fear of this resistance? Not at all my dear, simply know that there will be a resistance and that it is an indication that you need to make the process as natural as possible.    
If ever you feel like your old man isn't scared of anything and is the toughest cookie you have seen in the world, just know that there are days when your old man would go and get the sweetest doughnut and milkshake possible to calm himself before a meeting that he's anxious about. This is after he is trying his best to cut out sugar as much as possible.    
Adding on to how scared your old man is, he was scared of moments where his friend circles would combine as well and he was scared of telling the truth to one friend that he's hanging out with another friend instead. These are things that I'm still trying to grow out of with the help of slowly putting myself out there. The fear of rejection and being left alone is strong no matter what. So know that you are not alone, to feel alienated and left alone is to be human as well much like its counterpart. Have faith in yourself that you would retain the friends that would be by your side in times of need.    
Your old man used to drink a lot back in the day. I think that should have been pretty obvious to you as well. On the beginning of this year I decided not to drink again for three months. At first it was presented as a challenge by a friend that I do not consider a close friend anymore, but later on I realized that this was sort of a practicing ground for me when you would be coming around in to the world my dear. And so I began and one month went by with triumphant glee. But as the end of the second month rolls around the stress rises high, it is clear that alcohol was a way for your old man to numb his pain and to escape from reality. It was a form of self harm after a while where I purposefully would reduce my thinking capabilities as a punishment for not being able to find a solution through the struggles that life had to offer. Regardless, your old man persisted to this day and has not sabotaged himself with alcohol and he would not be doing it in solidarity when you are coming around to this world.     

Date: 21.02.2025      
To: The one after my own heart      

I made it to this morning. Today is one of those days that made me say this out loud. I stood my ground yesterday and I realized that some people are not open to seeing a world view outside of their own. And at times like that I need to protect myself above all. I hope to god that I do not pass on the same trauma that I had to endure, but if I have, forgive me my dear, it was never my intention to do so. And if you are currently at a state where your self esteem is low and you are teetering towards the precipice of taking your own life, please take a moment to know that no matter who might find you unworthy you need to stay by your own side the most. Why you might ask, well simply put there's still a life left to live and experiences to be had. There is still always something that can be done with the life that we have regardless of what gets taken away from us. Do not abandon the inner child within you, that child has already gone through enough as it is. Don't pile on top of the damages that have already been dealt.        
I do not have a lot to talk about except that there were many moments your old man decided not to walk this earth anymore and take the final leap ahead of time. I hope by the time I get to know you most of these tendencies would be faint as it can get. It is quite comforting to abandon your child if that is all that you have known as the reality. But in reality there are people who might help out and it requires a phenomenal strength to take the first step to ask for help.     
Try your best not to doubt yourself based on one dimension of evaluation. You might not be good at something based on an arbitrary standard set by someone else, but you can be good at something else in the standard that you set by yourself. We are people with multiple facets. An art exhibition of sorts. Some paintings might not appeal to some and some paintings might not appeal to anyone but the fact that they came and the fact that as a collective you are not a bad art exhibition is undeniable. If there is at least one good quality in you, at least one good skill that you have, then hold fast to it. Even if we are to live in the most poorest state that we can, we will still somehow manage our lives.        

I promise you that I will live to see you someday.       

Date: 22.02.2025     
To: The one after my own heart      

I made it to this morning as well. Yesterday was difficult in terms of the emotions that I had to deal with through out the day. First came a puppet with the face of a martyr that I had to deal with, and then came the two injuries that happened on the badminton court. It is interesting to think that your old man would take responsibility of people falling over and spraining their ankle when he booked the badminton court. Logically, yes it doesn't make sense for me to be guilty for the injury that I didn't accidentally cause. However, there is the emotional component that makes me feel that this wouldn't have happened if.... and that is where I get stuck. There is nothing for me to do. It was simply out of my control. Yet I want to take responsibility for it. Why? I'm not certain either. Perhaps by the time you are reading this I might have a better idea but for now all I know is that it's easier to blame myself than to blame bad luck. Perhaps it is my trauma from my childhood where I would be blamed when the electronics didn't work in the house. Regardless I need to accept that I did the best I can do to make sure that everyone was kept safe.       
There will be times in your life when you are met with a strong feeling of abandonment. It could come when those you trusted to take your side in times of difficulty betrays you to take the side of the majority. At such times, keep in mind that everyone is doing it for the sake of their safety and while it may seem unfair it doesn't do you any good to hate on them. First and foremost do not desert yourself in these times. Do what is necessary, healthy and sustainable for you to feel happy and loved at that moment. Do not be the tyrant that deprives you of the little joys in life for the sake of delaying gratification. When times are rough and there is an opportunity to make yourself feel loved as long as the price of having that joy doesn't harm you in the long run.     
Sometimes it's good to let your anger out to a confidante that you trust to listen and not to judge. Men really need to build relationships with other men where they are free to cry and let their tears fall. It is a man's innate nature to hold back their tears as that's what was being taught since they are young (at least it was for me). The gender stereotypes that I grew up with might have vanished by now hopefully. If it is still prevalent in the society, it would take the form of "don't cry like a girl". The statement itself is nonsensical because the ability to cry is the first demonstration of life in a new born baby. They say that the first and last breath are the hardest to take and hence why we cry in pain in both moments. For those who decide to take their last breath ahead of time the cries of pain are more prominent closer to the act.
In life you will need to decide when to take a break from putting in the extra effort for people that do not value your expertise. If you have no choice but to interact with these people then give them the bare minimum you need to give them while also feigning an empty poker face.

Date: 23.02.2025       
To: The one after my own heart      

I'm feeling a lot better today I would say. Not much to give as a letter from yesterday apart from realising how much of a difference it makes to stay in the presence of someone and just kick back and relax compared to staying at home and trying to relax. Platonic friendships can be quite useful at times like this. Your old man has given up hope finding a partner at this stage so there is no way that I would be spending my time trying to court anyone. It is also fascinating to realise that you are not alone in the way you behave inside the house. Most people who live by themselves prefer to live in their house with a certain way that they would not want to change, and to be a good friend means to be able to accommodate that.      
Also I hate the smell of cheese and I honestly do not find it appealing at this point.      

Date: 24.02.2025      
To: The one after my own heart      

Sometimes it's freeing when you start living life purposefully. It starts with enjoying the most mundane moments of your life. It can be simply enjoying the stars at night, or it could be just seeing the contrasting colors of bright green leaves reaching up high into the dull gray skies.       
People used to say that your old man has a face that has subtitles underneath it all the time, because no matter what it was easy to read his emotions through his face. Perhaps that might still be the case and if that's the case I hope you have not learned the skill of trying to read people based on their emotions. It is not a superpower at all, but merely a survival tactic learned in a household where emotions aren't expressed or communicated properly. Hence why I hope you would never end up in such a position.          
If you tend to have a negative outlook towards yourself, that same outlook would seep into how you view other people as well. You would consider their one mistake as the end of the relationship with them, which is why you fear making a mistake in a relationship and prepare yourself for abandonment, perhaps even premeditate the abandonment in a self fulfilling prophecy. I am someone of that sorts and I hope you are not. Life will throw you a bunch of the same lessons to learn when you realise how bad you are at something. For me these days it's accepting people's mistakes and their hurtful actions towards me. I would tend to invalidate all their past goodwill simply by one mistake they did because I would start questioning the past and its genuine nature. Perhaps this is because of how my childhood abuser would always provide a lot but in turn also weaponize them when abusing me. Perhaps I am only protecting myself, or I am projecting my fears onto them. Either way I will be trying to take this week slowly to fully understand what's going in my head and how I approach people.      

Date: 25.02.2025     
To: The one after my own heart      

Your old man is officially divorced and single now. The news didn't come as a shock but rather a soft sigh. There's a soft beauty in unspoken goodbyes. That is what I believe is the main story for this week.     
It might already be obvious but your old man can be quite angry and stubborn at times. From a young age, I did not have the proper tools to let go of my anger. In a household where negative emotions are shunned, it is natural for the child to learn only passive avoidant ways of dealing with anger. Therefore for me it is difficult to understand what's the right way to express my discomfort. It's even worse when it's against someone who I'm afraid of.      
During difficult time periods it can be easy to lose sight of the things that you can be grateful for and simply force yourself to target short term wins while sacrificing your health. That was a fact, but the question on how you are going to avoid doing that is something I'm yet to find the answer for.     
Yesterday was a barrage of unanswered questions that I will hopefully find the solution to slowly.      

Date: 26.02.2025      
To: The one after my own heart      

There's a lot of people supporting your old man, I must say my dear. As much as I hate the outside world, sometimes I forget that there are people to support me if I get stuck with mr problems.      
That being said your old man is also very scared to take unorthodox decisions, or decisions that will put him at a place of social scrutiny. It literally sends shivers down my spine when I have to take a choice to be an independent person. It's not easy, yet it is even more harder for my overanalyzing brain that worries about every little detail that could happen as a result of my decision.        
One thing I will tell you from the time you are growing up, my dear, sugar is a devil that you should associate gently. Know that while you are young you might be able to excessively consume it, but with age comes a bigger health risk that I simply cannot emphasize. If you are coming close to your 20s my dear, please consider cutting out the sugar in your life slowly. You will realize how difficult it is to cut the sugar out but it takes time.     
As a final closing note, perhaps one of the most difficult things to do in life is to carve out your own path. I believe I was raised to believe that if you say no to someone's help then you will never have that person's help in the future. So it is a bit difficult for me to comprehend a world where I travel alone and do my own thing and be good at it.      
So if you are struggling now to figure out your life, my little one, know that your old man is still struggling even when he's near 30 years old.

Date: 27.02.2025      
To: The one after my own heart       

Yesterday was trippy little one. I had to confront a lot of the doubts and fears that have been circling my mind. At the time of writing this, I do not think I would be seeing you in the future, nor will you exist to read these. So I would have to drop these series to make sure I do not exhaust myself and give unnecessary hope.     
It is sad but at the moment I believe my life would be best targeted towards me reaching towards the goal of finding peace within me and I doubt it would be made easy unless I commit to it now. Perhaps there might be a flaw in the way that I am thinking where I do not need to take on this path by committing in this manner. The only analogy I have for everything right now is to think of it in terms of archery, and in this case, I think instead of committing to something right now planning for something at the end of the process seems forced and unnatural. If I were to go with the flow and be detatched in letting the archer and archery be separated I think it might be best for me to not jump to conclusions up front. So instead I will be focusing on sharing what I learn about finding inner peace with you my little one.      

Date: 28.02.2025      
To: The one after my own heart      

Everyday I get new ideas and things that I can do to get through the issues that I am struggling with. I will always say this, I am forever grateful for the friends that I have around me right now, despite what they might do in the future, right now I am grateful and glad that I have them.        
I am yet to figure out how to get my life back int otits previous form. Perhaps we might not be able to always perform the same routine through out the time as there will be days where you are not in the best mood to start your day in an upbeat format. For now I think we might need to focus on sleeping at an earlier time to properly fix my sleeping schedule.    
Perhaps in addition to these letters I can work on writing a small novel to read to you when you are little. I don't know if you want to listen to your old man's stories when you are young but I feel it would bring a bit of whimsy and beauty to mine and your life.    
Growing up you will come to a time where you would forcefully stay away from things that you enjoyed it, in fear of being addicted to it. In such cases, if it brings an innocent joy to you, or if you are at a place where there aren't a lot of things that bring joy to your life, it might actually be benficial to actually get into that activity that gives you joy. Have faith in yourself that you are capable of staying true to yourself and staying away from the addiction. Sometimes we strive hard trying to avoid being the state of flight, freeze, fight or fawn but we never stop to consider that sometimes these mechanisms are there for a reason and it might be necessary for us to calm ourself rather than to strive against it.       

Date: 01.03.2025      
To: The one after my own heart       

Your old man is technically two months sober. It was not easy as I thought it would be. Perhaps the most difficult part was the constant reminders all around in mass media and everyday life. Not to mention the friends suggesting to drink. So far have I gained any special abilities and such? Nope the only ability I obtained was to look for alternatives to numb the emotional and mental pains that I had to deal with.       
I still struggle to fix my sleeping schedule. I stay up watching movies that I have watched, or trying to find new ones to watch, all the while shoving unhealthy servings of sugary treats. Sugar is menance I will tell you that much. It's a quick fixer when you are feeling sad or any other negative emotion. It's a crutch basically and fighting against it is difficult when you also have the trauma to work against as well.          
I will need to get my life in order today and figure out the path forward, while also being kind to myself and taking care of myself. It's tough but reinventing yourself every week by reassessing who you are is a crucial thing to do I feel. Above all I need to rethink where I am going with the research work that I am doing, and to think of an outlet to pour my creative writing strengths to.      
These are all good questions that I hope to answer someday, but until then, I will keep on looking.     

Date: 02.03.2025     
To: The one after my own heart      

It's getting harder to wake up early and get on with the day with haste. I might be sleep deprived and still recovering or it could be the sudden loss of sugar that's causing me to be lethargic. If this is what it means to be a dependent on sugar then I believe sugar is worse of an addiction compared to alcohol.     
I believe I overwhelm myself quite easily by putting too much emphasis on one day and the requirement to finish all my work on a given day where if I succuumb to the desire to rest or engage in anything frivolous I would panic extensively on the day slipping between my hands. The concept that _Time is finite_ while literally might be motivating it can be also quite demoralising when your body demands rest or when your mind demands to freeze while stuck in the throes of an emotional flashback.      
In my opinion, my dear little one, it's best to take the route that is kinder and loving to yourself. Take care of yourself to make sure that you have food to eat, a clean bed and area to live, clean clothes to wear and contentment in life to keep on going forward.      

In our pursuit of liberation from wordly desires we tend to forget that by looking inward and loving ourselves we maybe closer to understand the world around us. For the wave is part of the ocean while also being a part of its own.   







