--- 
title: "On finding balance"
draft: true 
--- 

The way I see it there are multiple activities that need to happen. 

First we have the two activities of setting up rhythms and microcommitments, and tracking said rhythms and microcommitments by listening to your body and self. 

Then we have the activity of grounding ourselves to make sure we don't hyperfixate on one thing and forget to take care of ourselves. 

In addition to identifying the tasks that needs to be done perhaps we can also think about the shift in the mindset as well. It's overwhelming I know. It's scary to be honest to take that leap into a new mindset that feels alien.

So let's start with the basic key ideas that we want to take out from today's exercise.

You don’t have to “win” every day—just honor where your energy flows and ebbs.
See if you can notice the thoughts that occur when you are going down in a downward spiral, and announce that these are simply old wirings that were set up as a survival mechanism
Look at mistakes as data and not as verdicts. A mistake is not a reason for punishment but just a single data point in a sea of positive and negative instances. Your internal model needs to readjust to accomodate and make that same mistake again and if you do then we would just put a bit more weight in for that instance or see if that instance was actually a mistake or not. 
Forgiveness isn’t a one-time thing—it’s a muscle you build

Rhythms are better suited for you than routines. Build in options, not obligations. You are creating a menu of things you want to do. Not a rigid set of tasks to achieve. Shift the entire mindset from a todo list. What you now have small microcommitments, that you can start on and leave at if you don't have the energy. Each day you are listening to your body's energy and playing along with it. You are setting up a living landscape, where you take one week at a time and focus on the things that you need to accomplish by that week and the rest are put into later and someday. You are not forcing yourself to do things by obligation you are instead listening to your body and mind to feel what sort of activity works for you from the list of available activities for a given energy level.  

