--- 
title: "What I believe and where I will go ahead with my life"
--- 

What do I believe in? 

I was a Buddhist by birth. And I misinterpreted buddhism because I interpreted that lust is a bad thing that needs to be quelled completely and that the mind is a rabid wild animal that needs to be contained. I tried my best by meditating as much as I can until my self hatred couldn't go on any further and decided that I needed to die. And thereon I decided to let go of Buddhism and be agnostic. While it is true that Buddhism was not the culprit in what I was feeling, the fact that I held on to Buddhism in the wrong method is what drove me to let go. A relgion of compassion and acceptance and kindness should not be making their followers feel suicidal at the thought that they are not good enough or flawed in the eye of the religion.  

From that moment onwards, I have been exploring different philosophies and trying to understand what they had to offer and what was the core principal that buddhism was trying to explain. 

After ages of searching, I have decided it's best to put myself out there and simply say what I believe in and what I want to practice in life. 

Put simply what I believe is that one must first focus on their breath and be in the present moment. Feel your breath and understand that you are a valuable human being simply because you are breathing and being alive. Not because of your accomplishments, not because of other people liking you, not because of your usefulness. You are valuable and worth loving simply because you are a living breathing human. You are imperfect yes but so is everyone and your imperfections makes you human and a part of a bigger collection. Stand in a busy shopping center, look at all the people walking by, look at them and see that all of them are valuable simply because they are breathing, notice their breath from the outside if you can and breath with them, you are both generating energy and being alive together, what a wonderful feeling it is that you and so many other people in this world are breathing and alive. Look at all these strangers again and notice the tiny imperfections that they might think about, imperfections that the society has imposed on you and on them as well, notice how all of these imperfections make them human. Now look at a newborn baby in one of those strollers, are they not perfect, beautiful as they are, do we not say they are adorable and cute even after their 7th fall they get back up for their eighth walk. When in their journey of life do we consider them imperfect? Are they imperfect when they are entering school? Are they imperfect as they experience their heart break? Are they imperfect as they walk down the aisle in a wedding attire? Tell me then where did you start considering yourself imperfect? Who's considering us imperfect, we are all perfect in this very moment despite whatever is happening in our lives. We are all imperfect yet perfect valuable breathing alive human beings that deserve to see the beauty of the present moment. 

We have limited breaths in this life. Every little project you work on that you might have discarded is still valuable. Spend your breath on things that matter to you.

The main philosophy that I understand is that,    
Breath and be in the present moment, feel the sensations in your body fully,      
Accept and sit with the thoughts that come to your head without any judgement or criticism, simply observe and sit with the thoughts,     
You are loved and valued as you breath and be in the present moment regardless of what state you are in currently,     
You are not alone, you are alive with so many other people, you are your individual person with your own story but you are also part of a huge collective of humans and animals that breath and live with you,          
You are imperfect and that makes you human and still loved and valued, there is no point in life that you become imperfect unless you decide to set an external rule that deems you as imperfect, but even with that rule in place you were still perfect at certain times in the future, so what purpose do these rules even serve if they are only valid for that one instance,        
Breath and be in the present moment, and let thoughts pass through you without any judgement, do not act upon them, slowly take your time and with an intent on seeing the world for what it is without any judgement of good or bad. Do things not for the sake of good or bad but because they are the kindest things to do.          
