# On chasing dreams

Ever since I was little, I do not remember exactly when, I would be interested in a weird variety of topics and have the wildest dreams children can have. That is one of the sweet innocenct qualities that children possess, the naive optimism and whole hearted belief that things are possible if you try doing it. We dress up and act as our parents when we play tea party or play houses, even though we have zero knowledge on the actual weight of being a parent or a breadwinner. We simply know the individual traits and actions to mimic of certain characters. Similarly when we were little we would have high hopes on we would want to become. There was so much potential within us as we would loudly proclaim in a room full of strangers or acquaintances that we would one day be teachers, doctors, pilots, astronauts or engineers. We had no clue on the exact implications, the process, the requirements but we loved dreaming about them. We would do and act as if we were that person to embody that dream. And as anyone who is reading this already knows, those dreams soon fade away and are replaced with things and we never expected yet we enjoy or are neutral towards the things that we are currently doing. 

In my early school days, I would be interested in a variety of hobbies. To put it short I would be doing robotics and electronics for a few months and then moving on to cardistry. It led to my parents believing that I would not commit to anything when I start something new, and I can't blame them. After seeing a person not being able to commit many times, your internal bias starts growing that this person would always shift from one hobby to another. But I have stuck with a few hobbies that I found interesting, and all the hobbies that I left out gave me stories and experiences that I can use to relate to people from different areas. 

This chapter is for those who are lost on feeling like they have a lack of purpose or they have too many opportunities and can't pick any. While it is possible such a person might have an Attention Deficiency Disorder where they have a hard time regulating attention, I would forego that usual recommendation to go seek medical help and talk about how to make the best and accept the situation we are in. Why would I avoid the usual recommendation? For one, if you can make the best out of the hand you have been dealt and you are happy and content with the life that you currently have and it is built in a way that is sustainable for you in the long run, is there a reason to seek medication to be a fraction of a finer version of yourself? And second I'm not a medical professional to diagnose your condition to simply put the fear of a mental condition in your head. However, if by following other's advices you still seem to struggle and your current condition is negatively affecting your life constantly, I would suggest that you go and seek medical attention. The bottom line is that what I have to give in this chapter are my thoughts and exercises that I use to handle my situation and it is of noway an fool proof guide or a litmus test for mental conditions. 

Now after that train wreck of a derailment, let's get on with the rest of the conversation. What were we talking about? Chasing dreams and choosing opportunities. Well in life what I have found out to be the main lesson in my search was that, anything you learn will be of use someday, even if it shapes the way that you percieve or act upon a task. An student learning to be an accountant decides to switch careers and becomes a chef. Does that mean all of his knowledge in balancing ledgers are gone to waste? Probably, but the foundational skills of seeing the finer details, making comparisons and processing information in a faster way might be helpful when they are dealing with new recipes, food or even if they start their own restaurant. It could be that the student didn't actually gain any skills from the accounting class, but still it might just provide a good icebreaker over a fellow workmate, or even a prospective partner in the future. In my native tongue there is a saying which translated means, "The one thing that thieves or your enemies can't steal from you are the knowledge and skills you have gained". While it is quite a useful saying for a parent who wants to encourage their children to study harder, it does also have a bit of wisdom in it. For those who feel like they have been set back in time because they wasted so much time learning something useless, just know that those skills will come in handy someday, everyone is on their own timelines and we decide how we want to play the hands we have been dealt. People who might be ahead of you in the new career that you are stepping in to might have spent ages honing their skills in that area but you also have something that you bring to the table. It might be a set of small napkins but those napkins might be the reason that someone gets to have a clean meal. 

If the case is that whatever you learn will be useful to you in the end, what should someone do when feeling lost of having no purpose or having too many opportunities to pick from? Pick one and strive hard at it and see if it fits you. Yes I hear your woes of not having enough time. Time is running out, yes, and employers won't hire people who are near retirement age, yes, and therefore you need to take the best decision that you can make right now to get to the top as fast as possible. The question then becomes, is it the case that when you do find the thing that you love, it would be difficult to make a living out of it because people would not be willing to pay for it? That might be true in certain professions, but I believe wholeheeartedly with the innocent child in me that there will always be a way to make a standing for yourself and earn enough to live a content life. Mind you it might not be a luxurious life, but it might be enough for you to survive. Life isn't easy when you bring money into the picture. Money brings a lot of imbalances and injustices to this world. It might not be entirely the fault of money but it does have a say in how your life is structured. 

Coming back to our original question and answer, there is a certain idea that Cal Newport had brought up in his book, "So good they can't ignore you". His idea was that in summary, you should not chase your passions and instead should work hard on one thing until you become passionate about it. This brings us back to the original topic of how children proclaim their passion. They have no clue of what is needed to be a pilot, they just learned what the letter G looks like much less feel multiples of them on their body as they fly an aircraft. Our passions are determined when we are young by the idea of being a certain person, not the by the idea of having to work hard to be that person. A child sees a violinist on stage and falls in love with the idea of being able to create such wonderful music. His passion is to be a violinist and then he decides to pick up the violin and learn it. Lo and behold the sound of screaming cats fill the room in the first attempt. The setback doesn't bother him as he keeps on practicing determined to be the person he wants to be. But everyday his practices drive him further away from that dream as he realizes how much he has to learn. Evidently he gives up on it. On the other hand he picks up the flute just because he could whistle a bit and gives it a go. He has no vision or any high standard of who he wants to be. He is simply focused on having fun blowing wind into the flute. Little by little, it gets to him that he is capable of something as he focuses primarly on just playing the flute. Soon he's playing in the same stage as the violinist that he once aspired to be but in the wind section.

So what was the lesson here? Pick one task, focus on the present moment and focus on the foundational skills and find enjoyment in it, use your dreams as a rudder but never as a whip on yourself. Eventually things will fall into place. Time is running out for everyone, money is hard to come by, but if we were to die tomorrow tragically, wouldn't we rather die living a content life than a rich one?