# On helping others and expecting help 

Almost everyone in their life has helped another person at some point or the other. Either by obligation or by kindness. What I will be talking about in this chapter is about the ways that people help each other, the morality of helping others, how people burn out from helping others and finally the expectations of receiving help.

Kindness is an obvious reason to help others. However, the real question is why are we being kind to this person. For many they feel a sense of sadness, empathy for the other person and thereby a desire to help comes into mind. There are other reasons that people help others. One would be to feel a sense of power or the other person. In this case people would feel that sense of sadness because they believe they are far ahead or in a better position in life. There is a slight tendency of some people in this category to impose their idea or help simply because they are better at it. In such cases it is best to avoid the help of such people although it might come at a price of actually being helpless. I personally prefer to preserve my autonomy than to give it away and follow someone else's ideas blindly. That sounds a lot like I'm stubborn and whether you view it as a good or bad quality depends on the perspective you have on the quality. A stubborn detective chasing down a crime scene and not taking other's opinions is accoladed when he turns out to be right while the stubborn man who sticks to his conservative ideas deeply is shunned. The same quality can be beneficial and harmful in certain scenarios. 

People tend to have a certain repulsion to help others who are way ahead of them in life and seem to be extremely resourceful. I have that tendency and I shroud it under the name of being efficient in who I am helping. The analogy being that there is no point to filling an cup that is already filled to the brim and is overflowing. One might argue that the person who already has a lot of help might not be receiving the right type of help and that I might be the person who can actually give the exact help they need. I must admit that is rare, partly because what I have to offer is in no way unique or extravagant. Therefore if I feel like this person will find a replacement help in case I am unavailable I would put less effort on to it. In a way, that is the way that I try to feel valued in life, where I feel important and responsible. 

This feeling of being valued for your help comes from my childhood from what I have discovered through my therapy sessions. Growing up my parents always taught me to help others in need and it was accepted in the family that you are only useful in the household if you provide some help. Which is true in a way because maintaining a household is a collective effort. However, the slippery extreme of this becomes where you would not be able to exist in a place where your help is not needed, and my dear reader, we often will find ourselves in such places. In such cases, accepting that your value in life is not defined by the amount of help you do to others is crucial. I will add more on this on the chapter about the value of life (See @sec-on-the-value-of-ones-life). The gist of the idea is that the value of a person's life is not measured by the help they give at a certain point in time but by the energy, personality and effect they have on other people. You might be in a completely new country unable to help anyone at all and you will spiral thinking you are not useful, believe me for I have been there. The reality is that there are things that you give to others by default unseen which includes the overall energy, compassion and empathy you bring to the table. 

Another side effect of this extreme is that you would be unwilling to accept help unless you have shown that you can bring something to the table. This becomes increasingly frustrating to people who want to help you out when you are starting off new or if they have walked the path that you have walked in. I had to deal with many people like that and this aversion to accepting help has to come with time as they slowly learn to accept that getting help without any expectations is not wrong. My main argument I bring in such scenarios is that by not allowing others to help you, you are also depriving them of the opportunity to help you making them feel sad, frustrated and worried as they see that your current situation can be improved with what they have.I have tried to push myself away from that idea, into a state where I accept people's help even if I can't help them at the moment or maybe ever in the future. However, this also can be seen in a different perspective of me being selfish. The fine line between these two states are defined by the moment I refuse to help when asked for help, until then I can not proved to be selfish. However, be weary when accepting help from others, for sometimes people who want to give help might have an ulterior motive.

Regarding those who do not want to accept help from others, there is also the case that they might already have people to help and your help might not exactly be needed. When giving help some people might not want to accept help because they have already established support networks. This is a hard pill to swallow but in most cases if you are a newcomer to an already established ecosystem it might be hard for you to find your place in this network where and who you can offer your help to. What I have learned is that I will offer my help and leave the door open for others to seek help while in the meantime I try to help myself by working on myself to be more useful, and also by accepting help from others to build trust and connections. There will always be a niche or something that you bring to the table and there will be someone who wants exactly that or something similar. Have faith in yourself and work on strategizing what you believe you can give best, is it quality or quantity or consistency or spontaneity?

While helping people out there is a slight chance of us feeling burnt out from helping a lot of people. 