# On meditation, mindfulness and being present

Where do I even begin? There's already so many books out there about the different methods and techniques to meditate. Add on top of that a dozen or so more books on building habits and staying consistent. What in the world could I possibly offer that has not already being covered in such a vast majority of literature? 

Simple. I will walk through you what I feel and what I think about, so that it gives you a bit of clarity on whether what you are feeling is valid or even better yet whether what I'm feeling is invalid or not. 

Before we begin, I must bring forward a tid bit of my past relationship with meditation. I must for a chapter without a few personal anecdotes would be incomplete. My relationship with meditation started when I was first interested in getting rid of the thoughts that began to take center stage in my mind as I was going through puberty. The whole reason why I got into it will be detailed out in a separate chapter. For now, bear with me. In my earliest meditation practices, I was told that the mind is like a fish thrown out of water, desperately jumping here and there and never settling. I was told that the mind was a bull that is running here and there madly and meditation was the leash that you use to tie to the center. And as the bull struggles more and more you slowly shorten the leash to bring the bull closer. Mind you, I was 16 years old at this time and I accepted the argument that yes my mind is the enemy that I must conquer somehow. And that ladies and gentleman is where I got off on the wrong foot to begin with. I trained hard to meditate. I was trying my best to stay consistent and I would have long meditation sessions some even spanning to 30 or more minutes of sitting in one place and waging war with my mind trying to tame it. The word tame is an interesting choice coz some of the Buddhist texts that I grew up with had phrases that had similar meaning to taming or subduing your mind. However, as you might find out in other chapters, this sort of extensive battling with my mind ended up with my mind breaking and snapping back at me, driving me to my first suicide attempt. After that incident, I stepped out of Theravada Buddhism and meditation for a while and began searching for the true meaning of meditation. It was once I was out there looking at other forms of Buddhism and meditation that I started to get an idea about what exactly was to be done with meditation.

Your mind is not your enemy. Let me make that perfectly clear here. You are not waging a war. There are no enemies. Remove the judgement that you have in your head towards whatever quality that you seek to get rid of through meditation. Meditation isn't a way to destroy or make your mind work right. It is simply for you to observe and be aware of your mind. 

I have a really vague memory of a story that I once learned back when I was learning about meditation that made a lot more sense now. One time, a monk (I'm not sure if it was Lord Budhha or not) was walking with one of his followers and witnessed a sort of a circus show done by a man who was capable of standing on the top of a pole with just the tip of his finger. The monk told his follower, "Imagine you are that performer with your entire focus on that one single point. Now let go of that one point. That is similar to what happens with meditation". 

In meditation, what I do is to simply first make peace with myself. As someone who has dealt with a lot of negative self talk and went through depression and sucidal thoughts, the first thing you need to be is kind to yourself. When I was first learning meditation in the temple, I always wondered why would anyone need to be kind to themselves? Isn't that something that people always do by default? Little did I know that there is actually a possibility for a person to fully despise themselves to the point of hating the very breath that they take in. Life can be full of surprises and the naive optimism of a young child always amazes me. 

The way I calm myself is by first focusing on my legs and telling myself gently and kindly to relax my legs and I purposefully relax my legs with a clear intent. And I work my way upwards to my head. As I get more and more used to this routine, I have the tendency to try and speed up the process by instructing myself quickly to relax myself. And that is where I catch myself and start again to slow myself down and reassure myself that we are not running out of time. 

This is another point where I would want to talk more about. The Buddhism that I knew when I was young always talked about making haste because the time you have on this life is precious and you must meditate and work towards nirvana without any delay. While I understand the sentiment, I believe there should be a small fine print underneath that says "Hey you should make haste, seize the day and what not, but do it slowly. Make haste, slowly. Take your time, be kind to yourself, every step you take is still valuable, you are not late, there is always time, just keep at it and you will get to a better place than before".

<!-- Talk more about the way that you meditate, on how you clear your mind and observe and how to bring this to the outside world and what to do when you fail to keep track of your thoughts.  -->