---
title: "On the harm we bring upon ourselves"
---

Blood, sweat and tears. That is what has made my work the way that it is right now. People often ask how is it possible for one to harm themselves. How is it possible for a person to hold a knife to their skin and drag it with enough pressure and intent to draw blood? The answer is pretty simple, hate yourself until your entire being wishes that the next breath you take is the last. And from there on you are never ever coming back from the hell of self hatred. 

All those who preach self love, I ask them, have you considered the fact that sometimes some poeple might have a self that they don't want to nurture. It's our responsibility, yes, we got here by such a slim chance, but that is no guarantee that the person that is born from all of this will be someone who the world wants to accept. Natural selection comes in a way to weed out the weak from this world, the more you hate yourself the more that others find you despicable and so on and so forth until all that is left is the scarred husk of who you once were. It's futile to expect that a person broken like me, with low standards, with low self control, with no boundaries, would make it  through in life. If said person does then it's at the cost of not having the strength to live or the will to persevere. 

I do regret all those that had to endure my presence. As much  as they wanted to save me, I have realized that it's only a waste of timn and energy. Death is a comfort in a way tbh. Sadly there aren't any ideal  opportune days to die. Too many criterias to satisfy. The future looks quite bleak as I realize more and more the hell I have  dug for myself. I was destined to be in this state from the beginning wasn't it?  It is only an inevitable when the  time comes for you to take that step. Surely and eventually you will have to find a way to end things here even if it's another failed attempt. Even if it means being sent to the hospital to be recovered as a defeated  weakling you are. Why do we breathe? Why do we struggle to keep our bodies alive only to see the shame, destruction and pain that it wrecks on those around us.