---
title: "On the fear of being alone"
---

In the fears that the primitive human has given us, being alone is a significant one, similar to the fear of death. There are some who are able to live their lives in solitude and thrive in such an environment. There are also those who need human interaction to function. The term that people loosely use for this divide is extroversion vs introversion. The main idea that I have surmised and internalized after talking with many people about their individual definitions of extroversion vs introversion is that people who feel energized after spending time with groups of people are extroverted compared to introverts.

As it might be clear to anyone who interacted with me past high school would know, I am an extrovert. It was interesting to see the change in my behavior prior and post high school years. I believe it was during the time of hormonal storms that I decided to be introverted and shut myself off from the world while after the storm subsided I found joy in engaging with people. Discovering the stories that people have to say about their successes, their lessons learned, their failures, their hopes and dreams was truly gratifying. 

However after being put in a series of difficult situations I started to realize that I was being an extrovert in order to avoid the fear of feeling alone. 