# On writing and other creatives

I was never a writer to begin with. To be fair, when we are little we do not have predetermined artistic desires blessed upon us by the muses. My earliest creative aspirations was in drawing funnily enough. It was a peaceful and easy way for my parents to pacify me whenever they needed to keep me occupied. Simply put a box of crayons and sheets of papers infront of me and I would be content for the entire time period. I did get carried away with my drawing obsession soon enough to the point that I would use drawing as a distraction from the actual studying or exam preparation that I was supposed to do. Sadly though, despite my best efforts I still to this day lack the skills to be a good artist. The first obstruction I had when I first started was that I would find it difficult to decide on which colors to choose, leaving behind a trail of line drawings that my sister would sometimes take into her hand to color. However, with time I started develop a slight sense of how colors work as I moved to the graphic design and eventually I was able to understand how the colors should match in a design upto a certain level, however by that time I was unable to make any good looking line drawings. In life you gain one skill at the expense of losing one skill I believe, even though the former skill might be heavily dormant and requires a massive amount of work to get back into a working state. There was a brief period of time where I decided to revive the skill with an obsession on learning how to draw human figures in Japanese manga drawing style. This led to a wide variety of portraits that I drew by looking at reference images and tutorials online.

Apart from drawing, another creative obsession that began during my young years was the ability to write. It was first inspired I believe when I used to keep a small notebook containing different thoughts and quotes that my mind came up with. Eventually I had racked up about 4 80 page A6 notebooks that contained myraid thoughts and observations. It was fascinating to look back and see the first tell tale signs of my writing career. Soon the short thoughts became poems and I wrote many poems in my native language. However, for a period of time my creative writing aspirations were put on hold as a new found obsession in computer science made me focus primarily on honing the logical thinking hemisphere of my brain. Luckily, after coming to college and as I began looking at life in a novel perspective, my creative flair rose back in the form of short stories and attempts at novels. And as the drawings have gone the short stories and novels never actually saw an end or a completion of any sort. I do not know if I can call myself a writer with only a handful of poems that are available online and no actual published work, self published even. Regardless I shall try to write and finish a book someday and I hope this book becomes the one that I finally get to finish. 

Apart from creative writing, through out my academic career I have always been required to write articles, papers in a academic writing setting. The main difference I see in academic writing compared to creative writing is the change of voice in my head. The words that pour through my fingers are directed by a small voice that is telling me what to write next. That same voice is what's powering the words you see on this book. When I'm told to write an academic article, the voice changes drastically to a somewhat of a careful, tactical voice with a slight pinch of pompousness mixed into it. I'm not exactly sure what causes this shift in tone in the voice inside my head, perhaps it's the way that I read the academic articles that make me mimic the same tone that I read the papers in. I do try to bring my creative voice into the academic writing setting but it very rarely mixes well and quite often the more logical voice takes over as I pour out more of the theoretical aspects of my work.