---
title: "Notes to those I leave behind"
--- 

Simply put here I will be putting behind what I want to tell the world what goes through my mind when I'm about to end my life. Hopefully if it does happen someday, eventually, for I'm sure that it will, I hope that someone might be able to read this to know that the decision wasn't fueled by a single thought but a cumulative build up of pain and trauma. 

Each day I will add on to the previous thoughts that existed. Perhaps reading the previous thoughts might deter me from executing any plan. If not at least there is a concise flow of thoughts before my end.

**Date:** 29.08.2025      
To: Those who I leave behind

I'm sorry you have to read these notes. But better you know about what goes through my mind instead of having to guess what was the cause of my end. Look at my life, what is there to take from it.... 
I shouldn't be saying these things, cause I'm simple reinforcing these thoughts, but why do I think about recovery and healing? What's worth living for honestly? Why am I fueling a broken vessel as I am. I keep saying that I'm valuable for simply existing and breathing, but in reality I can't see it honestly. I tell others about it, but I honestly don't feel it truth be told. I don't know what it is to be loved unconditionally... how can I convince myself that I deserve to be loved in that way when I haven't even experienced it. The rage I feel deep inside right now to lash out and let the anger towards myself to burn myself entirely, it's intense and immense, I must say. If it wasn't for the witnesses I would have executed my plan. 
I realized that I tend to ideate my funeral and my death as it is a pleasant fantasy to have when life becomes stressful. It's comfortable to imagine how your death would mean nothing in all the friend circles and all the connections around you. It's comfortable because right now you feel as if your work is absolute shit, there's nothing for you to be proud about. And it feels true, and I don't want to say if it's true or not because I don't know if it's actually true or not. I don't want to reinforce anything that might backfire. 
There's a small part of me that tries to focus on recovery and healing meanwhile the other side simply sees all the work as a lost cause and that either we make the absolute best result or our work is just utter garbage. I don't know which side to take on honestly.
All I know is that, after my death, I will be forgotten and possibly gone unnoticed. I have no inherent value or utility value right now. I am replaceable. That is what I'm hearing right now. I do not know if it's the truth but that is what I'm hearing. Sure anyone reading this might try to come up with a thousand and ten ways to show that I'm needed, but the reality is that life goes on so fast that my death will probably not be significant in many people's lives. There's so much happening everyday that I can guarantee that while I might occasionally cross people's minds, there won't be cases where my absence will be felt heavily. I'm sure of that. 
I talk about how people are valuable and worthy of love simply because of them being born and existing. Yet I myself know that doesn't really make a person valuable. It doesn't right? Am I giving in to the capitalist idea that my value is based on how memorable I am and how useful I am. 
I have a huge amount of rage within me. Who is this rage aimed at? Myself of course. What am I trying to achieve by being angry at myself like this. I just hate the fact that I'm such a lousy piece of shit. I'm not stable and I don't think I should continue in this state. I want to fucking die for fucks sake why is it that so complicated. Every little thing irritates me and I want to fucking rip the ever living shit out of my body. I hate myself. Truly I hate myself so much, I don't know how else to put it.  

**Date**: 30.08.2025     
To: Those who I didn't leave behind    

I survived somehow and that's important. I will keep on practicing what I did earlier to heal and recover. Being mindful and aware of my thoughts is hard when the focus of the thought is on my inadequacy honestly. It's easy to get caught up in it and rush into working on things day and night until the satisfaction of being valuable again comes up. The prize I pay to chase after a fleeting feeling of being valuable and accomplished. Happiness was always gained by action not by inaction. Very rarely you would find happiness by simply existing. Even a gift was a sign that you were useful and memorable for a person, not as a sign that you are loved regardless of my utility value or how memorable I am.

