# Why am I doing this?

> Do not go gently into that good night, ... ,
> Rage, rage against the dying of the light

They say whenever you feel like giving up on something or not feel motivated, you should always try to think of the reason why you started writing this. In my case, I believe it's best I keep a list of reasons why I wanted to write this book. They might not exactly be bullet lists. As you might have noticed, my thinking pattern is more towards the long form of writing and not exactly towards short concise and precise articulated points. 

One reason that I can see is that there are people who might have gone through a set of experiences similar to mine or might have observed someone going through something similar. Perhaps this book will give them insight on their thought patterns. I haven't really identified a reader audience and tailored this book towards a specific audience. But on the off chance someone stumbles on this book and finds it interesting I hope it helps them get a new perspective on life. 

Another reason is that I believe that my way of thinking is a bit different to others. How modest of me, to think that I'm unique to others. Well in reality I am. Each person who reads this book has a completely new perspective in life. In a world of unique people, does being unique become normal? I hope not. Normalcy requires that everyone follows the same predictable pattern, but if everyone is different and unique in the way of their thinking, then I believe being unique still holds value. An interesting argument that I have read from a book on Zen Buddhism was that every person in this world are unique while also being part of _oneness_ (I'm not sure what the exact label to put, Daoism calls it the Dao and you might call it Mother Nature). That's just a side tangent that I wanted to put in there.

Regardless, if my thinking pattern is unique and not the same as everyone else, then I believe there is something for others to read and understand from my perspective hopefully. Even if it is to read this and understand that "This is not the way a person should be thinking". That is still progress. Everyone's working hard to write books on how to do things right. No one tries to write a book on One of the thousand ways of doing things wrong.

Finally, the reason I write this book is to leave behind my thoughts for others in the case of untimely death be it self inflicted or natural or tragic. As the first quote goes, I do not want to give up without putting down everything that I have thought of and felt in this life. 
